### ISSUE TITLE
unknown place to signup

### ISSUE THREAD

**Issue by Subroutine7901** [Repl-it-Coders/About-Page#10]
so, on the readme, it says that you can make an issue on the repo to sign up, and as the signup on the site has been disabled, i need to find that repo, please tell meh and maybe put it in the readme also, the readme seems to belong somewhere else, like on the website, maybe make one for the repo

**Comment by Subroutine7901** [comment]
also, i'm @williham on repl.it and ik it's replit.com that just seemed weird i have repldm btw

**Comment by Subroutine7901** [comment]
@whippingdot hello!!!

**Comment by Subroutine7901** [comment]
meow

**Comment by darkdarcool** [comment]
> meow

First off, why did you put that comment, and second, wait until @whippingdot comes on to approve you joining the org. But I'm fine with it.

**Comment by Subroutine7901** [comment]
1. i said meow because i was bored
2. great!
3. also, are you in to crypto like dogecoin?

**Comment by darkdarcool** [comment]
Cool

And no. Maybe my dad, but me no

**Comment by Subroutine7901** [comment]
ok

**Comment by Subroutine7901** [comment]
but my question wasn't answered, what repo do i do the issue?

**Comment by whippingdot** [comment]
@ColePete umm I don't remember the link so can you send it to @willcatmeow ?

Also @willcatmeow i will add you when I get on my comp, and if Cole doesn't send the link to the repo, I will.

I was on vacation for some days and I just came back, sorry I didn't reply.

**Comment by whippingdot** [comment]
BTW i deleted the repo cause it was needed. Just create an issue if you want to join the repo. Can someone add that change to the website / README?

Also join [here](https://github.com/Repl-it-Coders)

**Comment by darkdarcool** [comment]
@whippingdot, it wouldn't be hard for me to make a small repo for the signup page?

**Comment by Subroutine7901** [comment]
well, i guess this is that issue now, maybe make that repo again, and thanks!

**Comment by darkdarcool** [comment]
@willcatmeow kk
