### ISSUE TITLE
join

### ISSUE THREAD

**Issue by xItzDiamondx** [Repl-it-Coders/About-Page#11]
can i join, i have repl.it

**Comment by darkdarcool** [comment]
what languages do you know?

**Comment by xItzDiamondx** [comment]
JS, CSS, HTML, Git, Java, SCSS.

**Comment by darkdarcool** [comment]
Can I have your replit profile link?

Also rate your skill in those languages, and give me a repl and repo confirming you know the lang. If you don't have one, make a repl in the lang displaying your skill and give me the link for everything, you don't have to inv me, spotlight page is good

Also sorry for late reply 

@whippingdot, can you also help with this application

**Comment by xItzDiamondx** [comment]
In HTML i'm a 9/10 my website is a good idea. [website](https://www.xitzdiamondx.github.io)

**Comment by xItzDiamondx** [comment]
In CSS I'm a 9/10 as well, my website is also a good idea.

**Comment by xItzDiamondx** [comment]
for js as well, and for SCSS there was one the responsive nav bar, but i changed it because it wouldn't work in GH Pages.

**Comment by xItzDiamondx** [comment]
Sure, here it is. I haven't made much in Repl.it https://replit.com/@xItzDiamondx
***@***.***ItzDiamondx

**Comment by darkdarcool** [comment]
Do you have a Java repl or repo? Also the website isn't there

**Comment by xItzDiamondx** [comment]
http://xitzdiamondx.github.io/ Sorry for the late reply, I was animating.

**Comment by xItzDiamondx** [comment]
I don't have a Java repl or repo, because I am currently learning.

**Comment by whippingdot** [comment]
You have been on replit for one month, so I am okay with you, but it is up to dark

**Comment by darkdarcool** [comment]
@whippingdot, I don't have a problem with @xItzDiamondx joining. I'll add him and I'll also add him to the groups.(if I can figure it out)

**Comment by xItzDiamondx** [comment]
Cool, thanks!

**Comment by darkdarcool** [comment]
lol, fast reply, lemme add you!

**Comment by darkdarcool** [comment]
Your added, please go [here](https://github.com/Repl-it-Coders) to accept!

**Comment by xItzDiamondx** [comment]
lol

**Comment by iop3** [comment]
also @whippingdot can i be a mod too?

it's okay if i can't just asking.

###### also im like active on github for 24/7 (kinda) so yeah

I have no idea why im talking about that here but whatever

**Comment by whippingdot** [comment]
You might be able to replace @BD103 if he leaves, we will see

**Comment by iop3** [comment]
why will bd103 leave? @whippingdot

**Comment by BD103** [comment]
We weren't doing anything on the org. And also if I'm to be frank:

I'm tired of all the people spamming me with notifications that just lead to people saying "haha e." This is not a professional environment, and I just don't find it fun anymore.

I'm sorry, @whippingdot.

**Comment by iop3** [comment]
so................................................................does that mean your leaving.................................so......................................................am i a mod now?.............................

**Comment by darkdarcool** [comment]
Maybe.

**Comment by iop3** [comment]
:O

**Comment by iop3** [comment]
do i like...get any special tOoLs?

**Comment by darkdarcool** [comment]
No

**Comment by darkdarcool** [comment]
Special project? Yes. Perms? Not for you yet

**Comment by iop3** [comment]
oh then what's so special about being a mod.

**Comment by darkdarcool** [comment]
Why do you want to be one? What special things have you done for the community?

**Comment by iop3** [comment]
oh oof. didn't think about that.

**Comment by iop3** [comment]
(i dont need to be a mod actually i was just wondering lul)

**Comment by darkdarcool** [comment]
lol it’s fine to ask and wonder, but think about how you being a mod will benefit the community

**Comment by iop3** [comment]
oh that's what you mean.

**Comment by iop3** [comment]
what does a mod even do in Repl-It-Coders?

**Comment by darkdarcool** [comment]
Moderate mainly, have special projects, and lead the direction of community projects

**Comment by iop3** [comment]
oh.

**Comment by darkdarcool** [comment]
Also you should, but don’t  need to be a OK coder in at least one lang

**Comment by iop3** [comment]
so u (cuz ur a mod right?) could kick people?

**Comment by iop3** [comment]
lol

**Comment by iop3** [comment]
jk

**Comment by darkdarcool** [comment]
I mean yes, with owner perms, but only as a last resort

**Comment by iop3** [comment]
oh.

**Comment by iop3** [comment]
actually nah im good. no need to be a mod.

**Comment by darkdarcool** [comment]
I would also discuss it with my fellow moderators

**Comment by iop3** [comment]
alright.

**Comment by darkdarcool** [comment]
Ok, but if you wanna be a mod again, make sure that you becoming a mod would be beneficial to the community

**Comment by iop3** [comment]
kk thanks for the help (~~did you even help me lul~~)

**Comment by darkdarcool** [comment]
All I did made make you seriously think about you becoming a mod

**Comment by iop3** [comment]
:)

**Comment by darkdarcool** [comment]
;)

**Comment by iop3** [comment]
;3
