### ISSUE TITLE
Should i add mine or no @whippingdot

### ISSUE THREAD

**Issue by iop3** [Repl-it-Coders/About-Page#12]
Should i add my portfolio or no?  @whippingdot

**Comment by whippingdot** [comment]
Ya you can

**Comment by iop3** [comment]
ok

**Comment by darkdarcool** [comment]
@iop3, when are you going to come onto the repl?

**Comment by anonymt-dev** [comment]
When is someone going to realize that I'm no longer 'CodingRedpanda' and change that, and that my website for it is old now, so I'd rather use my [theiocoder.is-a.dev](https://theiocoder.is-a.dev) site (I can change all of that but, has *anyone* realized?)
