### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by Isaiah-Day** [Repl-it-Coders/About-Page#4]
A lot of the pages here are misspelled, and few have correct punctuation. We should at least check the non-profile pages before publishing, maybe even the profiles.

**Comment by darkdarcool** [comment]
I agree. I think we all need to put our text into a grammar and spelling check website before putting it in code.

**Comment by whippingdot** [comment]
I did, I used VS Code spell check...But check manually if u want

**Comment by darkdarcool** [comment]
lol I'm too lazy to do that.
