### ISSUE TITLE
Dark Mode Glitch

### ISSUE THREAD

**Issue by darkdarcool** [Repl-it-Coders/About-Page#5]
Hi! 
So while I was testing out the site's new dark mode, I found a glitch to the toggle. When you turn dark mode on, and go to one of our members profile, and go back to the main page via back arrow, the dark mode toggle is reversed. Like this:
![image](https://user-images.githubusercontent.com/66882633/108840492-700e3e00-75a4-11eb-8f00-5797e5d93241.png)

You can see the dark mode toggle is on, but the page isn't changing. When you click on the toggle again, it does nothing, (well is goes to light mode, which we are already on). Then if you hit it a second time, it finally goes to dark mode. 

I think to fix this we should default to dark mode? 

I don't know much about javascript so this issue may take time.

PLZ fix!

-darkdarcool

> lol why did I sign off on this you know this issue was opened by me

**Comment by whippingdot** [comment]
> lol why did I sign off on this you know this issue was opened by me

lul ya also don't flex that u r a mod on this org (it doesn't help in any way)
Also, I noticed this but if we default to dark mode and we switch to light mode then when we press the back arrow it will be stuck the other way. There is no fix like that. Someone must fix it. The thing is the website knows you pressed the toggle switch, but it takes it from last time, so it thinks it is already dark mode and it doesn't put dark mode. Leave this as it is (unless someone can fix it)

**Comment by darkdarcool** [comment]
Yeh okay(sorry for flex, I took it out)

**Comment by darkdarcool** [comment]
Looks like no one can fix its so I'm closing the issue(i don't think people will actually notice)
